sudo: false
cache: bundler
rvm:
  - "2.3.0"
addons:
  postgresql: "9.4"
services:
  - redis-server
  - postgresql
bundler_args: "--binstubs --without production"
before_script:
  - bundle exec rails assets:precompile
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - psql -c 'create database travis_ci_test;' -U postgres