sudo: false
cache: bundler
rvm:
  - "2.3.0"
addons:
  postgresql: "9.4"
services:
  - redis-server
  - postgresql
bundler_args: "--binstubs --without production"
before_install:
  - "export DISPLAY=:99.0"
before_script:
  - RAILS_ENV=production SECRET_KEY_BASE=waffles bundle exec rails assets:precompile
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - 'sh -e /etc/init.d/xvfb start'
  - psql -c 'create database travis_ci_test;' -U postgres