sudo: false
cache: bundler
rvm:
  - "2.3.0"
addons:
  postgresql: "9.4"
services:
  - redis-server
  - postgresql
install:
  - bundle install --binstubs --without production
  - bundle --version
before_install:
  - "export DISPLAY=:99.0"
  - gem install bundler -v 1.16.0
  - bundle --version
before_script:
  - bundle exec rails assets:precompile
  - bundle exec rails db:create
  - bundle exec rails db:migrate
  - 'sh -e /etc/init.d/xvfb start'
  - psql -c 'create database travis_ci_test;' -U postgres